package com.patientsky.recruitment.rol.domain;

import lombok.Data;

import java.util.Date;

@Data
public class Interval {

    Date Start;
    Date end;
    int intervalMinutes;

    //Autogenerated Getters and Setters using Lombok
}
